{% set name = "jupyter-dash" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-dash-{{ version }}.tar.gz
  sha256: d546c7c25a2867c14c95a48af0ad572803b26915a5ce6052158c9dede4dbf48c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - ansi2html
    - dash
    - flask
    - ipykernel
    - ipython
    - python >=3.5
    - requests
    - retrying

test:
  imports:
    - jupyter_dash

about:
  home: https://github.com/plotly/jupyter-dash
  summary: Dash support for the Jupyter notebook interface
  license: MIT
  license_file: LICENSE.txt
  description: |
    This library makes it easy to develop Plotly Dash apps 
    interactively from within Jupyter environments 
    (e.g. classic Notebook, JupyterLab, Visual Studio 
    Code notebooks, nteract, PyCharm notebooks, etc.).

extra:
  recipe-maintainers:
    - raybellwaves
    - bandersen23
