{% set name = "jupyter-dash" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-dash-{{ version }}.tar.gz
  sha256: eb5eb42ec8cb5e3388d41d895b5ef6e66812e3345cb271cc374318a1a589e687

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - ansi2html
    - dash
    - flask
    - ipykernel
    - ipython
    - python >=3.5
    - requests
    - retrying

test:
  imports:
    - jupyter_dash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/plotly/jupyter-dash
  summary: Dash support for the Jupyter notebook interface
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
